[build]
  command = "cd backend && npm install && npm run build"
  functions = "backend/netlify/functions"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend && npm run dev"
  port = 3000
  targetPort = 3001
  framework = "vite"